{% set name = "harlequin-databricks" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin_databricks-{{ version }}.tar.gz
  sha256: 4d4d2a5ce34541fddd05990afa4aec0b73088d023dbcdc013984c6d6290c9a3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - harlequin >=1.24.0,<2.0.0
    - databricks-sql-connector >=3.0.3,<4.0.0
  run_constrained:
    - databricks-sdk >=0.30.0

test:
  imports:
    - harlequin_databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexmalins/harlequin-databricks
  summary: A Harlequin adapter for Databricks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
    - alexmalins
