{% set name = "harlequin-databricks" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_databricks-{{ version }}.tar.gz
  sha256: 2f2ddf3f214d7c3f6a72716cab66b15a6277e57a696e5417cb479ae8351c60fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - harlequin >=1.25.2
    - databricks-sql-connector >=3.7.0
  run_constrained:
    - databricks-sdk >=0.40.0

test:
  imports:
    - harlequin_databricks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alexmalins/harlequin-databricks
  summary: A Harlequin adapter for Databricks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
    - alexmalins
